version: "{build}"

branches:
  only:
    - master

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release
  - Debug

matrix:
  fast_finish: true

environment:
  matrix:
  - solution_name: c-dojo.sln
    cmake_location: c

before_build:
  - mkdir .build
  - cd .build
  - cmake --version
  - cmake ../%cmake_location%

build_script:
  - msbuild %solution_name%

